security:
    encoders:
        FOS\UserBundle\Model\UserInterface: bcrypt

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH, ROLE_EDITOR]

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username_email

    firewalls:
        main:
            pattern: ^/
            form_login:
                provider: fos_userbundle
                csrf_parameter: _csrf_token

            logout:       true
            anonymous:    true

            http_basic: ~

    access_control:
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/product/*/edit, role: [ROLE_ADMIN, ROLE_EDITOR] }
        - { path: ^/admin, role: [ROLE_ADMIN, ROLE_EDITOR] }
        - { path: ^/product/new, role: [ROLE_ADMIN, ROLE_EDITOR] }